apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.enableTLS }}
  tls:
    - hosts:
        - {{ default ( printf "%s.lehre.ris.bht-berlin.de" .Release.Namespace ) .Values.fqdn }}
      secretName: '{{ default ( printf "%s-tls" (include "chart.fullname" .) ) .Values.tlsCertificateSecretName }}'
  {{- end }}
  rules:
    - host: {{ default ( printf "%s.lehre.ris.bht-berlin.de" .Release.Namespace ) .Values.fqdn }}
      http:
        paths:
        - pathType: Prefix
          path: '/'
          backend:
            service:
              name: {{ include "chart.fullname" . }}
              port:
                number: {{ .Values.service.port }}
