apiVersion: 'networking.k8s.io/v1'
kind: 'Ingress'
metadata:
  name: 'webservice-ingress'
spec:
  ingressClassName: 'nginx'
  rules:
  - host: webservice.mmi-devops-exercises.project.ris.bht-berlin.de
    http:
      paths:
      - pathType: Prefix
        path: '/'
        backend:
          service:
            name: webservice-service
            port:
              number: 80
