- hosts: 'instance_group'
  tasks:
    - ansible.builtin.import_role:
        name: 'webservice'
        tasks_from: 'install'
      vars:
        executable_origin: "{{ playbook_dir }}/../artifact.bin"
    - name: 'Configuration directory exists'
      ansible.builtin.file:
        state: 'directory'
        path: "{{ app_config_dir }}"
        mode: '0755'
    - name: 'Database password file exists'
      ansible.builtin.copy:
        content: "{{ database_password }}"
        dest: "{{ app_db_password_file_path }}"
        mode: '0600'

- hosts: 'backing_services'
  tasks:
    - ansible.builtin.import_tasks: './../tasks/install-redis.yaml'

- hosts: 'load_balancers'
  tasks:
    - ansible.builtin.import_tasks: './../tasks/install-nginx.yaml'
  handlers:
    - ansible.builtin.import_tasks: './../tasks/reload-nginx.yaml'
