nameOverride: ""
fullnameOverride: ""

image:
  registry: 'registry.bht-berlin.de:443'
  repository: 'fb6-wp11-devops/artifacts/webservice'
  tag: ':latest'

environment: 'production'

replicaCount: 1
port: 3000

# NOTE: may be provided via command line option
fqdn: null

resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 512m
    memory: 512Mi

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsUser: 65534
  capabilities:
    drop:
      - ALL


service:
  type: ClusterIP
  port: 8080


ingress:
  class: 'nginx'
  annotations: {}
