apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "chart.fullname" . }}-tls'
type: kubernetes.io/tls
data:
  tls.key: {{ required "ERROR: tls.key required!" .Values.tls.key | b64enc | quote }}
  tls.crt: {{ required "ERROR: tls.crt required!" .Values.tls.crt | b64enc | quote }}
