{{ if .Values.enablePersistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'pvc-database'
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}
