workflow:
  rules:
    # NOTE: run pipeline if commit is to a Merge/Pull-Request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    # NOTE: run pipeline if commit is directly pushed to certain branches
    - if: >-
        $CI_PIPELINE_SOURCE == "push"
        && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "stable")
      when: always
    # NOTE: Otherwise
    - when: never

variables:
  version: 0.0.$CI_PIPELINE_IID

stages:
  - test
  - build
  - publish


job_test:
  stage: test
  image: mirror.gcr.io/library/golang:1.21
  script:
    - go get -t ./...
    - go test -race -v ./...


job_build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /stable/
      when: always
  image: mirror.gcr.io/library/golang:1.21
  parallel:
    matrix:
      - os: 'darwin'
        arch: [ 'amd64', 'arm64' ]
      - os: 'linux'
        arch: [ 'amd64', 'arm64' ]
      - os: 'windows'
        arch: [ 'amd64', 'arm' ]
  before_script:
    - mkdir -p ./artifacts
  script:
    - go get -t ./...
    - GOOS=${os} GOARCH=${arch} CGO_ENABLED=0
        go build
          -o ./artifacts/webservice-${os}-${arch}
          ./*.go
  artifacts:
    paths:
      - ./artifacts
    expire_in: 10 sec


job_upload:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /stable/
      when: always
  image: public.ecr.aws/lts/ubuntu:22.04
  tags:
    - docker-privileged
  dependencies:
    - job_build
  before_script:
    - apt update
    - apt install -y
        ca-certificates
        curl
    - update-ca-certificates
  script:
    - |
      for artifact in ./artifacts/*; do
        chmod +x ${artifact}
        curl \
          --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
          --upload-file ${artifact} \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/artifacts/${version}/"
      done
