- hosts: 'instance_group'
  tasks:
    - ansible.builtin.import_role:
        name: 'webservice'
        tasks_from: 'install'
      vars:
        executable_origin: "{{ playbook_dir }}/../artifact.bin"

- hosts: 'backing_services'
  tasks:
    - ansible.builtin.import_tasks: './../tasks/install-redis.yaml'

- hosts: 'load_balancers'
  tasks:
    - ansible.builtin.import_tasks: './../tasks/install-nginx.yaml'
  handlers:
    - ansible.builtin.import_tasks: './../tasks/reload-nginx.yaml'
