- when:
    - executable_origin is not ansible.builtin.file
    - executable_origin is not ansible.builtin.url
  fail:
    msg: 'value of executable_origin not supported'

- when: executable_origin is ansible.builtin.file
  name: 'Install service from local file'
  ansible.builtin.copy:
    src: "{{ executable_origin }}"
    dest: "{{ executable_path }}"
    owner: 'root'
    group: 'root'
    mode: '711'
  notify:
    - 'restarting'

- when: executable_origin is ansible.builtin.url
  name: 'Install service from URL'
  ansible.builtin.get_url:
    url: "{{ executable_origin }}"
    checksum: "{{ executable_checksum }}"
    dest: "{{ executable_path }}"
    owner: 'root'
    group: 'root'
    mode: '711'
  notify:
    - 'restarting'
