# -*- mode: ruby -*-
# vi: set ft=ruby :


DIR = File.dirname(__FILE__)

SSH_PUB_KEY = File.read( "#{ DIR }/.ssh/operator.pub" )
DOMAIN = 'vagrant.local'
USERNAME = 'operator'


Vagrant.configure("2") do |instance|

    if Vagrant.has_plugin?( "vagrant-hostmanager" )
        instance.hostmanager.enabled = true
        instance.hostmanager.manage_host = true
        instance.hostmanager.manage_guest = true
        instance.hostmanager.ignore_private_ip = false
    else
        raise "Vagrant Plugin 'HostManager' is required"
    end


    instance.vm.box = 'ubuntu/jammy64'

    instance.vm.provider "virtualbox" do |vb|
        vb.name = 'my-instance-group'
        vb.gui = false
        vb.cpus = 2
        vb.memory = "2048"
    end

    instance.vm.synced_folder "#{ DIR }", '/vagrant', disabled: true

    # NOTE: the Host-Manager plugin is required for this to have an effect
    instance.vm.hostname = "pad.#{ DOMAIN }"

    instance.vm.network 'private_network',
                        ip: "10.0.11.22",
                        :adapter => 2

    # INFO: expose HTTP port to access service via Nginx
    instance.vm.network "forwarded_port", host: 8080, guest: 80

    # INFO: set up a user that can be used with Ansible
    instance.vm.provision "shell",
                          privileged: true,
                          inline: <<-SHELL
                              groupadd --force #{ USERNAME }
                              useradd --shell /bin/bash --home-dir /home/#{ USERNAME } --no-user-group --expiredate '' --password 'p@sSw0rd' #{ USERNAME }
                              echo '#{ USERNAME } ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
                              mkdir -p /home/#{ USERNAME }/.ssh
                              echo '#{SSH_PUB_KEY}' >> /home/#{ USERNAME }/.ssh/authorized_keys
                              chmod -R 700 /home/#{ USERNAME }/.ssh && chown -R #{ USERNAME }:#{ USERNAME } /home/#{ USERNAME }
                          SHELL

    # INFO: make sure Ansible requirements are met
    instance.vm.provision "shell",
                          privileged: true,
                          inline: <<-SHELL
                              apt update
                              apt install -y \
                                  python3
                          SHELL
end
