{{ if .Values.enablePersistence }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: '/data/{{ include "chart.fullname" . }}/'
{{ end }}
