{{ if .Values.enablePersistence }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "chart.fullname" . }}-db-credentials'
type: Opaque
data:
  password.txt: {{ required "ERROR: redis.auth.password required!" .Values.redis.auth.password | b64enc | quote }}
{{ end }}
