apiVersion: v2
name: webservice
version: '0.0.1'
description: A Helm chart to deploy the webservice on Kubernetes

type: application
appVersion: '1.0.0'

dependencies:
  - name: redis
    version: '18.6.2'
    repository: oci://docker.io/bitnamicharts
    condition: enablePersistence
