nameOverride: ""
fullnameOverride: ""

enablePersistence: false
enableTLS: false

image:
  registry: 'registry.bht-berlin.de:443'
  repository: 'fb6-wp11-devops/webservice'
  tag: ':latest'

environment: 'production'

replicaCount: 1
port: 3000

# NOTE: may be provided via command line option
fqdn: null

envVars: {}

resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 512m
    memory: 512Mi

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsUser: 65534
  capabilities:
    drop:
      - ALL


service:
  type: ClusterIP
  port: 8080


ingress:
  annotations: {}


redis:
  fullnameOverride: 'redis'
  image:
    registry: 'docker.io'
    repository: 'bitnami/redis'
    tag: '7.2.3'
  architecture: 'standalone'
  master:
    service:
      ports:
        redis: 6379
    persistence:
      existingClaim: 'pvc-database'
  auth:
    enabled: true
    usePasswordFiles: true
