FROM public.ecr.aws/lts/ubuntu:20.04_stable


RUN apt update -y \
    && apt install -y nginx

RUN sed -i 's/80/8080/' /etc/nginx/sites-available/default

ENTRYPOINT [ "/usr/sbin/nginx" ]
CMD [ "-g", \
    "daemon off;" \
]

EXPOSE 8080
