# -*- mode: ruby -*-
# vi: set ft=ruby :


DIR = File.dirname(__FILE__)

GUEST_USERNAME = 'vagrant'


Vagrant.configure("2") do |instance|

    instance.vm.box = 'ubuntu/jammy64'

    instance.vm.provider "virtualbox" do |vb|
        vb.name = 'my-box-id'
        vb.gui = false
        vb.cpus = 1
        vb.memory = "1024"

        vb.check_guest_additions = true
    end

    instance.vm.network 'private_network',
                        ip: "10.0.42.23",
                        :adapter => 2

    instance.vm.synced_folder "#{ DIR }", '/vagrant', disabled: true
    instance.vm.synced_folder "#{ DIR }","/home/#{ GUEST_USERNAME }/devops-tutorial"

    instance.vm.network "forwarded_port", host: 8080, guest: 3000
end
