roles: []

collections:
  - name: 'https://github.com/prometheus-community/ansible.git'
    type: git
    version: '0.11.1'
  - name: 'https://github.com/grafana/grafana-ansible-collection.git'
    type: git
    version: '2.2.4'
